"""Modifying autoincrement

Revision ID: 1fcad33485d3
Revises: 97aaf8ca33f0
Create Date: 2024-04-16 23:50:57.333287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcad33485d3'
down_revision: Union[str, None] = '97aaf8ca33f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
