"""Deleting relationships

Revision ID: 3528cad9b24a
Revises: 9a3ff8713a16
Create Date: 2024-04-17 00:40:46.041930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3528cad9b24a'
down_revision: Union[str, None] = '9a3ff8713a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
