"""Creating others tables

Revision ID: 97aaf8ca33f0
Revises: a2d530a3fd29
Create Date: 2024-04-16 23:47:59.718819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97aaf8ca33f0'
down_revision: Union[str, None] = 'a2d530a3fd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus', sa.String(length=30), nullable=False),
    sa.Column('building', sa.String(length=30), nullable=False),
    sa.Column('room', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrictypes',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('devices',
    sa.Column('serial_number', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('serial_number_device', sa.String(length=40), nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('name_metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['name_metric_type'], ['metrictypes.name'], ),
    sa.ForeignKeyConstraint(['serial_number_device'], ['devices.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('devices')
    op.drop_table('metrictypes')
    op.drop_table('locations')
    # ### end Alembic commands ###
