"""Changing to date_time in Metric

Revision ID: 9a3ff8713a16
Revises: df4f5770b695
Create Date: 2024-04-17 00:24:16.640087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3ff8713a16'
down_revision: Union[str, None] = 'df4f5770b695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.drop_column('metrics', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('metrics', 'date_time')
    # ### end Alembic commands ###
